package MyERP::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'MyERP::Schema',
    
    connect_info => {
        dsn => 'dbi:MariaDB:database=myerp',
        user => 'thomas',
        password => 'Seagull221@',
    }
);

=head1 NAME

MyERP::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<MyERP>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<MyERP::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.66

=head1 AUTHOR

Thomas Rio

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
